// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VarthexComanda.Infrastructure.Persistence;

#nullable disable

namespace VarthexComanda.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VarthexComandaDbContext))]
    partial class VarthexComandaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("VarthexComanda.Domain.BackupRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Arquivo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("arquivo");

                    b.Property<string>("Checksum")
                        .HasColumnType("TEXT")
                        .HasColumnName("checksum");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("destino");

                    b.Property<string>("Mensagem")
                        .HasColumnType("TEXT")
                        .HasColumnName("mensagem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("backup_registro", null, t =>
                        {
                            t.HasCheckConstraint("CK_backup_registro_status", "status IN ('SUCESSO', 'FALHA')");
                        });
                });

            modelBuilder.Entity("VarthexComanda.Domain.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categoria", null, t =>
                        {
                            t.HasCheckConstraint("CK_categoria_ativo", "ativo IN (0, 1)");
                        });
                });

            modelBuilder.Entity("VarthexComanda.Domain.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AbertaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("aberta_em");

                    b.Property<DateTime?>("FechadaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechada_em");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_cliente");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("TotalCentavos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_centavos");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("uq_comanda_numero_aberta")
                        .HasFilter("status = 'ABERTA'");

                    b.ToTable("comanda", null, t =>
                        {
                            t.HasCheckConstraint("CK_comanda_numero_positivo", "numero > 0");

                            t.HasCheckConstraint("CK_comanda_status_fechada_em", "(status = 'ABERTA' AND fechada_em IS NULL) OR (status IN ('FECHADA', 'CANCELADA') AND fechada_em IS NOT NULL)");

                            t.HasCheckConstraint("CK_comanda_status_valido", "status IN ('ABERTA', 'FECHADA', 'CANCELADA')");

                            t.HasCheckConstraint("CK_comanda_total_centavos_nao_negativo", "total_centavos >= 0");
                        });
                });

            modelBuilder.Entity("VarthexComanda.Domain.Configuracao", b =>
                {
                    b.Property<string>("Chave")
                        .HasColumnType("TEXT")
                        .HasColumnName("chave");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("valor");

                    b.HasKey("Chave");

                    b.ToTable("configuracao", (string)null);
                });

            modelBuilder.Entity("VarthexComanda.Domain.ItemComanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comanda_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_produto");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacao");

                    b.Property<long>("PrecoUnitarioCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preco_unitario_centavos");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantidade");

                    b.Property<long>("SubtotalCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subtotal_centavos");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId")
                        .HasDatabaseName("idx_item_comanda_comanda");

                    b.HasIndex("ProdutoId");

                    b.ToTable("item_comanda", null, t =>
                        {
                            t.HasCheckConstraint("CK_item_comanda_preco_unitario_positivo", "preco_unitario_centavos > 0");

                            t.HasCheckConstraint("CK_item_comanda_quantidade_positiva", "quantidade > 0");

                            t.HasCheckConstraint("CK_item_comanda_subtotal_igual_preco_vezes_quantidade", "subtotal_centavos = preco_unitario_centavos * quantidade");

                            t.HasCheckConstraint("CK_item_comanda_subtotal_positivo", "subtotal_centavos > 0");
                        });
                });

            modelBuilder.Entity("VarthexComanda.Domain.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("criado_em");

                    b.Property<string>("FotoArquivo")
                        .HasColumnType("TEXT")
                        .HasColumnName("foto_arquivo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<long>("PrecoCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("preco_centavos");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId", "Ativo")
                        .HasDatabaseName("idx_produto_categoria_ativo");

                    b.ToTable("produto", null, t =>
                        {
                            t.HasCheckConstraint("CK_produto_ativo", "ativo IN (0, 1)");

                            t.HasCheckConstraint("CK_produto_preco_centavos_positivo", "preco_centavos > 0");
                        });
                });

            modelBuilder.Entity("VarthexComanda.Domain.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("comanda_id");

                    b.Property<DateTime>("FinalizadaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("finalizada_em");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numero");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("CONCLUIDA")
                        .HasColumnName("status");

                    b.Property<long>("TotalCentavos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_centavos");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId")
                        .IsUnique();

                    b.HasIndex("FinalizadaEm")
                        .HasDatabaseName("idx_venda_finalizada_em");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("venda", null, t =>
                        {
                            t.HasCheckConstraint("CK_venda_status_concluida", "status = 'CONCLUIDA'");

                            t.HasCheckConstraint("CK_venda_total_centavos_positivo", "total_centavos > 0");
                        });
                });

            modelBuilder.Entity("VarthexComanda.Domain.ItemComanda", b =>
                {
                    b.HasOne("VarthexComanda.Domain.Comanda", null)
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VarthexComanda.Domain.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VarthexComanda.Domain.Produto", b =>
                {
                    b.HasOne("VarthexComanda.Domain.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VarthexComanda.Domain.Venda", b =>
                {
                    b.HasOne("VarthexComanda.Domain.Comanda", null)
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
